### ISSUE TITLE
It doesn't work in Unity 6 (6000.0.5f1)

### ISSUE THREAD

**Issue by TheXRMonk** [mob-sakai/UnityEventDrawerEx#19]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
It doesn't work in Unity 6 (6000.0.5f1)

**To Reproduce**
It's not being rendered.

**Expected behavior**
Should work.

**Screenshots**
![image](https://github.com/user-attachments/assets/fe2cdd64-fcde-43bd-adcc-8d03c8412a13)

**Environment (please complete the following information):**
 - Version 1.0.2
 - Platform: Windows Editor
 - Unity version: 6000.0.5f1
 - Build options: N/A

**Additional context**
We've used this package fine for a long time - but it just stopped working after unity upgrade. :(

**Comment by mob-sakai** [comment]
The issue is not reproduced on my environment...
- Version 1.0.2
- Platform: Windows Editor
- Unity version: 6000.0.5f1

BTW, your inspector seems to look different from the default one.  
Are you using any other editor extension plugins (like Odin, etc.)?
![](https://github.com/user-attachments/assets/58744f48-7d89-49cb-87b1-a7e77ede3d71)

**Comment by TheXRMonk** [comment]
Thank you for the hint! It was indeed a different package ([MyBox](https://github.com/Deadcows/MyBox/wiki/Tools-and-Features#reworked-unityevent-inspector)) that had a silent conflict. I'll open up a feature request on their GitHub to maybe integrate with this instead because their feature seems less useful. :)
